version: '3'
services:
    web:
        image: v1ll4n/api-server-base:latest
        volumes:
            - "./nginx-config/ssl:/etc/ssl"
            - "./static:/var/www/html"
        ports:
            - "8992:80"
        environment:
            # 设置 server name
            - SERVER_NAME=localhost

            # 设置 /api 开头的反代设置
            - REVERSE_PROXY_HOST=127.0.0.1
            - REVERSE_PROXY_PORT=8080
        restart: always